/** Crown Breeds — full EO / absolute / CO2 / resin catalog for formula builder. Merged into FB_ING.eo in formula_builder_tab.js */
function getFormulaBuilderEoList(){
  var T=function(a,b,c){return{low:a,mid:b,high:c};};
  return [
    /* —— True floral EOs —— */
    {id:"neroli",name:"Neroli (true EO)",desc:"Hero regenerating floral — cell renewal, anti-aging, brightening; linalool / nerolidol rich; precious top-note.",benefits:{regenerating:3,antiaging:3,brightening:3,calming:2},tips:T("Trace neroli — luxury signal already present.","Working hero dose — scent + skin narrative align.","Neroli-forward SKU — cost and allergens deserve label care.")},
    {id:"rose_otto",name:"Rose otto (true EO)",desc:"Steam-distilled rose — deeply hydrating story, brightening, extremely potent and expensive.",benefits:{moisturizing:3,brightening:3,calming:3,antiaging:2},tips:T("Micro-dose otto — potency even when barely listed.","Rose heart — justify price per jar at this share.","Rose-dominant — ultra-luxury positioning; watch dermal limits.")},
    {id:"geranium",name:"Geranium (true EO)",desc:"Sebum balancing, toning, rosy profile; bridges lavender and rose.",benefits:{acne:2,antiaging:1,brightening:1,soothing:2},tips:T("Soft rosy balance note.","Clear sebum-control story without medicinal edge.","Geranium-led — overtly rosy-floral; check sensitive users.")},
    {id:"yylang",name:"Ylang ylang (true EO)",desc:"Sebum balancing, exotic floral depth; sensitizer — cap near 0.8% of total batch in many references.",benefits:{calming:2,moisturizing:2,acne:1},tips:T("Safe floral sultriness — watch total %.","Approaching guideline ceiling — document for QC.","High ylang share — sensitization risk; reduce or redistribute."),potency:"strong"},
    {id:"chamomile",name:"Roman chamomile (true EO)",desc:"Redness, eczema, rosacea-friendly reputation; esters — strong anti-inflammatory calm.",benefits:{soothing:3,antiinflammatory:3,calming:3},tips:T("Gentle apple-hay calm layer.","Primary sensitive-skin EO pillar.","Roman-led — maximally soothing; pair with calendula in B if available.")},
    {id:"chamomile_german",name:"German chamomile (true EO)",desc:"Bisabolol / chamazulene — deeper anti-inflammatory than Roman; tints blue-green at meaningful use.",benefits:{antiinflammatory:3,soothing:3,calming:2,healing:2},tips:T("Trace azulene — cool blue story begins.","Visible blue tinge likely in pale balm.","German-led — pigment + potency; specialty 'blue balm' angle.")},
    {id:"palmarosa",name:"Palmarosa (true EO)",desc:"Hydrating, antibacterial reputation; geraniol — rosy-fresh, affordable geranium cousin.",benefits:{moisturizing:2,antimicrobial:2,regenerating:2,acne:1},tips:T("Rosy-fresh lift without rose invoice.","Balancing moist antimicrobial heart.","Palmarosa-dominant — spa-herbal rosy top.")},
    {id:"lavender",name:"Lavender (true EO)",desc:"Universal reference — calming, acne and minor wound folklore; linalyl acetate flagship.",benefits:{calming:3,acne:2,healing:3,soothing:3},tips:T("Clean herbal background.","Classic skin-safe pillar at modest share.","Lavender-forward — assertive herbal; some dislike the camphor edge.")},

    /* —— Resinous & woody —— */
    {id:"frankincense",name:"Frankincense (true EO)",desc:"Anti-aging, scarring, cell-turnover stories; boswellic-acid associations (distillate vs resin varies).",benefits:{antiaging:3,scarring:3,regenerating:3},tips:T("Elegant resin whisper.","Structured anti-scar / elasticity narrative.","Frankincense-led — church-resin dominant.")},
    {id:"myrrh",name:"Myrrh (true EO)",desc:"Anti-aging, wound healing, cracked dry skin; deep fixative resin.",benefits:{healing:3,antiaging:3,calming:2},tips:T("Sacred resin depth.","Repair and meditation-grade base.","Myrrh-heavy — thick sacred dust note.")},
    {id:"sandalwood",name:"Sandalwood (true EO)",desc:"Moisturizing, toning, long wear; alpha-santalol; costly.",benefits:{moisturizing:3,antiaging:2,calming:3},tips:T("Creamy wood whisper.","Premium dry-skin + scent anchor.","Sandalwood-led — budget and sourcing matter.")},
    {id:"cedarwood",name:"Cedarwood Atlas (true EO)",desc:"Calming, anti-inflammatory and anti-aging aromatherapy narratives; soft creamy wood.",benefits:{calming:3,antiinflammatory:2,antiaging:2,acne:1},tips:T("Blanket under florals.","Spa-forest body balm.","Atlas cedar-led — lumberyard cozy.")},
    {id:"cedarwood_virg",name:"Cedarwood Virginian (true EO)",desc:"More astringent, oily-skin and grounding story than Atlas; juniperene character.",benefits:{acne:2,calming:2,antiinflammatory:1},tips:T("Dry pencil-wood lift.","Oily-skin cologne base.","Virginian-led — sharper, more Texan fence-post.")},
    {id:"patchouli",name:"Patchouli (true EO)",desc:"Fixative base, anti-aging, cracked-skin salve history; earthy chocolate facet.",benefits:{antiaging:2,healing:2,moisturizing:2},tips:T("Clean hippie-chic anchor.","Long-lasting patch without dirt facet (quality dependent).","Patchouli-forward — divisive love-it note.")},
    {id:"vetiver",name:"Vetiver (true EO)",desc:"Deep grounding base, anti-stress, anti-aging cicatrizant folklore; smoky root.",benefits:{calming:3,antiaging:2,healing:2},tips:T("Smoke-root fixative thread.","Niche masculine prestige base.","Vetiver-led — campfire whiskey.")},
    {id:"spikenard",name:"Spikenard (true EO)",desc:"Rare earthy base — anti-aging, calming, biblical-luxury positioning.",benefits:{calming:3,antiaging:2,regenerating:2},tips:T("Holy-spoil niche whisper.","Meditation balm direction.","Spikenard-led — costly, intense earth.")},
    {id:"howood",name:"Ho wood (true EO)",desc:"Sustainable linalool-rich 'soft rosewood' — gentle anti-aging, calming.",benefits:{calming:3,soothing:3,antiaging:2,regenerating:2},tips:T("Innocuous woody linalool cushion.","Extends neroli/lavender cheaply.","Ho wood-led — sweet soft-wood perfume.")},
    {id:"copaiba",name:"Copaiba (oleoresin)",desc:"Beta-caryophyllene story — anti-inflammatory, amplifies other EOs perceptually; very mild scent.",benefits:{antiinflammatory:3,soothing:3,calming:2},tips:T("Cannabis-adjacent marketing without THC.","Boring alone — boosts resins.","Copaiba-high — still subtle; pair with bolder notes.")},
    {id:"cistus",name:"Cistus / labdanum (true EO)",desc:"Amber resin tightener, fixative, anti-aging leather-animal facet at high %.",benefits:{firming:3,antiaging:3,calming:1},tips:T("Warm amber flicker.","Niche ambergris alternative direction.","Labdanum-led — heavy leather/animal — choose audience.")},

    /* —— Herbaceous —— */
    {id:"clarysage",name:"Clary sage (true EO)",desc:"Hormonal-acne balancing; sclareol — avoid pregnancy / estrogen-sensitive users.",benefits:{acne:2,antiinflammatory:2,calming:2},tips:T("Intro hormonal-skin story carefully.","Working balance note for adult acne.","Clary-heavy — label pregnancy warning prominently.")},
    {id:"rosemary",name:"Rosemary (true EO, skin ct)",desc:"Antioxidant, anti-aging, circulation / stimulating; pick skin-appropriate chemotype — camphor CT can be harsh on face.",benefits:{antioxidant:3,antiaging:2,regenerating:2},tips:T("Spa herbal antioxidant lift.","Morning 'glow' stimulation narrative.","Rosemary-forward — risk Vicks vibe — dilute for face.")},
    {id:"helichrysum",name:"Helichrysum (true EO)",desc:"Scarring, regenerating — 'liquid gold'; neryl acetate flagship.",benefits:{scarring:3,regenerating:3,antiaging:3},tips:T("Even tiny % reads as repair SKU.","Sweet spot for scar balms.","Helichrysum-led — price per gram hurts.")},
    {id:"carrotseed",name:"Carrot seed (true EO)",desc:"Anti-aging, brightening, toning; carotol; earthy.",benefits:{antiaging:3,brightening:3,regenerating:2},tips:T("Rooty vitamin-A direction echo.","Pairs with rose or neroli in pro-age.","Carrot seed-led — soup celery note if clumsy.")},
    {id:"bluetansy",name:"Blue tansy (true EO)",desc:"Azulene-blue — redness, strong anti-inflammatory; tints balm; premium.",benefits:{antiinflammatory:3,soothing:3,calming:3},tips:T("Instagram blue trace.","Visible color at modest share.","Blue tansy-led — SKU is the color.")},
    {id:"yarrow",name:"Yarrow (true EO)",desc:"Chamazulene / chamazulene cousin blues — anti-inflammatory, wound redness, blue-green tint possible.",benefits:{antiinflammatory:3,healing:2,soothing:2},tips:T("Herbal blue-bitter whisper.","Outdoor first-aid romance.","Yarrow-led — very medicinal bitter.")},
    {id:"thymelinalool",name:"Thyme linalool (true EO)",desc:"Antibacterial / antifungal gentler than thymol CT; still respect dilution.",benefits:{antimicrobial:3,antifungal:2,antiinflammatory:2,acne:2},tips:T("Clean herbal without phenol burn.","Teen body-acne direction.","Thyme-forward — even linalool CT stings broken skin.")},
    {id:"sage",name:"Sage / Dalmatian (true EO)",desc:"Astringent, antioxidant, anti-aging; thujone awareness — not for pregnancy; not same as clary.",benefits:{antioxidant:2,antiaging:2,firming:2},tips:T("Sharp savory herb accent.","Oil-control cologne facet.","Sage-led — pizza + chemistry — rarely face-friendly at high share."),potency:"strong"},

    /* —— Citrus (cold-pressed called out in desc) —— */
    {id:"bergamotfcf",name:"Bergamot FCF (true EO)",desc:"Brightening, acne, calming — FCF = furocoumarin-free for leave-on when authentic.",benefits:{brightening:2,acne:2,calming:2,antimicrobial:1},tips:T("Verify COA is true FCF.","Earl Grey cologne bridge.","Non-FCF bergamot is not swappable on skin.")},
    {id:"lemon",name:"Lemon, cold-pressed (true EO)",desc:"Brightening, antioxidant; phototoxic expressed — body-heavy use or terpeneless / FCF-style grades for face/sun.",benefits:{brightening:3,antioxidant:2,calming:1},tips:T("Sparkle — document sun strategy.","Kitchen-citrus clean.","Lemon-heavy — phototoxicity risk if expressed + UV."),potency:"strong"},
    {id:"mandarin",name:"Mandarin (true EO)",desc:"Brightening, gentle, often friendlier to sensitive skin than lemon; still verify supplier photodata.",benefits:{brightening:2,calming:3,soothing:2},tips:T("Candy citrus whisper.","Baby-safe brand vibe at low %.","Mandarin-led — still citrus — mind phototoxicity tables.")},
    {id:"sweetorange",name:"Sweet orange (true EO)",desc:"Uplifting, antioxidant, affordable crowd-pleaser; expressed orange photonotes apply.",benefits:{brightening:2,antioxidant:2,calming:2},tips:T("Juice-box optimism.","Pairs vanilla and benzoin.","Orange-heavy — check IFRA + phototoxicity for your grade.")},
    {id:"grapefruit",name:"Grapefruit (true EO)",desc:"Astringent, brightening, oily skin; cold-pressed grapefruit is phototoxic — respect limits.",benefits:{acne:2,brightening:2,antimicrobial:1},tips:T("Pink bitter lift.","Morning toner energy in balm.","Grapefruit-led — phototoxicity + drug-interaction lore — label research.")},
    {id:"yuzu",name:"Yuzu (true EO)",desc:"Japanese citrus — antioxidant, brightening, unique aromatic (expensive).",benefits:{brightening:2,antioxidant:2,calming:2},tips:T("Niche Japanese fine-fragrance top.","Elevated yuzu marmalade.","Yuzu-led — pricey; verify adulteration.")},
    {id:"lime",name:"Lime distilled (true EO)",desc:"Clarifying, brightening; phototoxic if cold-pressed — use distilled for skin safety story.",benefits:{brightening:2,antimicrobial:2,acne:1},tips:T("Margarita soul without CP lime risk IF distilled.","Gin-cologne top.","If not distilled CP lime — phototoxic landmine."),potency:"strong"},
    {id:"petitgrain",name:"Petitgrain (true EO)",desc:"Oily skin, calming, woody-citrus; affordable neroli-tree alternative.",benefits:{acne:2,calming:3,soothing:2,regenerating:1},tips:T("Green branch neroli extender.","Unisex cologne water.","Petitgrain-forward — sharp laundry possible.")},

    /* —— Spice & root —— */
    {id:"ginger",name:"Ginger (true EO)",desc:"Warming, circulation, anti-inflammatory, antioxidant; spicy heat at high share.",benefits:{antiinflammatory:2,antioxidant:2,healing:2,regenerating:1},tips:T("Warm gingerbread thread.","Masculine winter sport.","Ginger-forward — hot rub — thin skin caution.")},
    {id:"cardamom",name:"Cardamom (true EO)",desc:"Warming, skin-softening, spicy-sweet chai note.",benefits:{calming:2,soothing:2,antimicrobial:1},tips:T("Luxury chai hint.","Pairs sandalwood/vanilla.","Cardamom-led — Nordic bakery spice.")},
    {id:"blackpepper",name:"Black pepper (true EO)",desc:"Circulation, warming, antioxidant, stimulating; can irritate.",benefits:{antioxidant:2,antiinflammatory:1,regenerating:1},tips:T("Sparkle without cinnamon burn.","Masculine lift over vetiver.","Pepper-heavy — sneeze + sting possible.")},
    {id:"turmeric_eo",name:"Turmeric (true EO)",desc:"Anti-inflammatory, brightening; generally less pigment stain than resinoid CO2 but still yellow risk.",benefits:{antiinflammatory:3,brightening:2,antioxidant:2},tips:T("Golden curry whisper.","Pairs frankincense.","Turmeric EO-heavy — color + curry smell — still stains some.")},
    {id:"clove",name:"Clove bud (true EO)",desc:"Antimicrobial, antioxidant; EU/IFRA caps near ~0.5% dermal in many tables — strong sensitizer.",benefits:{antimicrobial:3,antioxidant:2},tips:T("Christmas kiss micro-dose.","Toothache nostalgia — barely there.","Clove-heavy — numb lips + dermal danger — obey caps."),potency:"strong"},
    {id:"cinnamon_leaf",name:"Cinnamon leaf (true EO)",desc:"Warming, antimicrobial; leaf generally softer than bark; still caps ~0.6% in many references — high sensitizer.",benefits:{antimicrobial:2,antiinflammatory:1},tips:T("Holiday whisper only.","Chai depth with vanilla.","Cinnamon leaf-heavy — chemical burn risk — strictly body/low ppm."),potency:"strong"},
    {id:"nutmeg",name:"Nutmeg (true EO)",desc:"Anti-inflammatory, warming, circulation support folklore; psychoactive at absurd oral doses — irrelevant here but label sanely.",benefits:{antiinflammatory:2,calming:2,antioxidant:1},tips:T("Eggnog micro-thread.","Pairs sweet orange.","Nutmeg-forward — can read muddy-hot.")},
    {id:"angelica",name:"Angelica root (true EO)",desc:"Anti-aging, regenerating, earthy musk; phototoxic root — sun + leave-on caution.",benefits:{regenerating:2,antiaging:2,calming:1},tips:T("Green musk curio note.","Niche amber masculine.","Angelica-heavy — phototoxicity + cost — label warnings."),potency:"strong"},

    /* —— Needle & green —— */
    {id:"cypress",name:"Cypress (true EO)",desc:"Astringent, oily skin, circulation, deodorant-clean facet.",benefits:{acne:2,antiinflammatory:1,calming:2},tips:T("Forest deodorant lift.","Unisex thigh-chafe sporty.","Cypress-led — Irish Spring flashbacks.")},
    {id:"juniper",name:"Juniper berry (true EO)",desc:"Detox / purify marketing (lymph stories), astringent, acne and oily skin.",benefits:{acne:2,antimicrobial:2,calming:1},tips:T("Gin botanical sparkle.","After-hike foot balm.","Juniper-forward — turpentine if clumsy.")},
    {id:"pine",name:"Pine (true EO)",desc:"Antimicrobial, circulation, fresh invigorating needle note.",benefits:{antimicrobial:2,antiinflammatory:1,calming:1},tips:T("Sauna tree snap.","Pairs spruce or fir.","Pine-led — cheap cleaner vibe if low grade.")},
    {id:"firneedle",name:"Fir needle (true EO)",desc:"Anti-inflammatory needle, clean forest Christmas; grounding.",benefits:{antiinflammatory:2,calming:2,antimicrobial:1},tips:T("Clean snow-tree sparkle.","Pairs vanilla amber.","Fir-heavy — car-freshener if overdosed.")},
    {id:"spruce",name:"Spruce (true EO)",desc:"Anti-inflammatory, grounding; pairs cedar and fir in conifer accords.",benefits:{antiinflammatory:2,calming:2},tips:T("Lumberjack soft opening.","Winter muscle rub.","Spruce-led — very phenolic pine.")},
    {id:"teatree",name:"Tea tree (true EO)",desc:"Antibacterial, antifungal, acne; reference ISO for blemish — 'body only' mindset for delicate face at high blend share.",benefits:{antimicrobial:3,antifungal:3,acne:3,antiinflammatory:2},tips:T("Clean clinic accent.","Back-acne sport stick story.","Tea tree-heavy — nose + irritation — face caution.")},

    /* —— Absolutes —— */
    {id:"vanilla_abs",name:"Vanilla absolute",desc:"Warm sweet solvent absolute base; anti-inflammatory folklore; pairs neroli + patchouli.",benefits:{calming:3,antiinflammatory:2,soothing:2},tips:T("Fine fragrance vanilla gravity.","Gourmand amber anchor.","Vanilla abs-heavy — thick dark syrup — usually pre-diluted.")},
    {id:"rose_abs",name:"Rose absolute",desc:"Richer / different facet than otto; often more affordable than otto at fragrance parity; deeply floral.",benefits:{moisturizing:3,antiaging:2,calming:2},tips:T("Thick jammy rose.","Attar-lite positioning.","Rose abs-heavy — heady + sensitization — microdose.")},
    {id:"jasmineabs",name:"Jasmine absolute",desc:"Anti-aging story, mood-lifting luxury base; potent sensitizer — trace use.",benefits:{antiaging:3,calming:3,moisturizing:2},tips:T("One-drop megastar.","Indolic night-bloom.","Jasmine-heavy — headache + RIFM concern — reduce."),potency:"strong"},
    {id:"violet_leaf",name:"Violet leaf absolute",desc:"Green-floral leaf, cucumber vibe; anti-aging niche / distinctive luxury.",benefits:{calming:2,soothing:2,antiaging:1},tips:T("Cool couture green.","Unisex niche.","Violet leaf-heavy — harsh leafy methyl notes.")},
    {id:"labdanum_abs",name:"Labdanum absolute",desc:"Resinous amber-like fixative; anti-aging leather-amber direction.",benefits:{antiaging:2,firming:2,calming:1},tips:T("Warm sticky ambergris-ish.","Pairs vanilla benzoin.","Labdanum-heavy — barnyard leather — intentional only.")},
    {id:"benzoin_abs",name:"Benzoin absolute",desc:"Vanilla-balsamic warmth; soothing, skin-healing salve history.",benefits:{healing:3,soothing:3,calming:2},tips:T("Powdery vanilla resin.","Fixes citrus tops.","Benzoin abs-heavy — benzyl notes + stickiness.")},
    {id:"tonka",name:"Tonka bean absolute",desc:"Warm coumarin, fixative; pairs vanilla, tobacco, cocoa directions.",benefits:{calming:2,antioxidant:1},tips:T("Coumarin cookie whisper.","Gourmand amber extension.","Tonka-heavy — play-dough if clumsy.")},
    {id:"beeswax_abs",name:"Beeswax absolute",desc:"Honeyed waxy absolute — unique; pairs literal beeswax in formula story.",benefits:{calming:1,soothing:1},tips:T("Hive poetry trace.","True-to-raw-beeswax brand narrative.","Beeswax abs-heavy — fatty waxy overpower.")},
    {id:"tuberose",name:"Tuberose absolute",desc:"Intensely floral luxury; very expensive; heady intoxicating.",benefits:{antiaging:1,calming:2,moisturizing:1},tips:T("White floral nuke micrograms.","Evening perfume balm.","Tuberose-heavy — indolic blast + cost.")},
    {id:"mimosa",name:"Mimosa absolute",desc:"Soft floral-powdery, calming, gentle luxury.",benefits:{calming:3,soothing:2},tips:T("Heavenly soft pollen.","Paris-floral skin scent.","Mimosa-heavy — hay-fever metaphor — some dislike.")},
    {id:"oakmoss",name:"Oakmoss absolute",desc:"Earthy-mossy fixative — severely IFRA-restricted; use minimally in consumer IFRA contexts.",benefits:{calming:2,antiaging:1},tips:T("Chypre nostalgia trace only.","IFRA research mandatory.","Oakmoss-heavy — forbidden vintage zone — legal/IFRA minefield."),potency:"strong"},
    {id:"tobacco",name:"Tobacco absolute",desc:"Deep warm hay curing note; fixative; controversial branding angle.",benefits:{calming:2,antiaging:1},tips:T("Whiskey lounge whisper.","Daddy aesthetic cologne balm.","Tobacco-heavy — cigarette fears — brand carefully.")},
    {id:"orris",name:"Orris absolute",desc:"Violet-iris root luxury — anti-aging prestige; extremely expensive.",benefits:{antiaging:3,moisturizing:2,calming:2},tips:T("Luxury lipstick iris dust.","Pairs rose sandalwood.","Orris-heavy — bankrupt-the-batch pricing.")},
    {id:"peru_balsam",name:"Peru balsam",desc:"Balsamic-vanilla healing, wound-repair folklore — IFRA / balsam-of-Peru allergy cross-reactivity; patch test.",benefits:{healing:3,soothing:3,calming:2},tips:T("Skin learns allergy optics — disclose.","Warm vanilla-smoke bandage.","Peru balsam-heavy — dermatitis lightning rod — research IFRA."),potency:"strong"},

    /* —— CO2 extracts —— */
    {id:"vanilla_co2",name:"Vanilla CO₂ total",desc:"Truest vanilla scent profile; warm anti-inflammatory story; very workable in balm.",benefits:{calming:3,antiinflammatory:2,antioxidant:1},tips:T("Mainstream gourmand gold.","Pairs copaiba neroli.","Vanilla CO2-heavy — cost + thickness — often dilute.")},
    {id:"frankincense_co2",name:"Frankincense CO₂",desc:"Often higher boswellic resin acids vs steam EO — superior anti-aging marketing story per some suppliers.",benefits:{antiaging:3,scarring:3,regenerating:3},tips:T("Resin science flex SKU.","Layer with frank EO for complexity.","CO2 resin is paste-like — pre-blend for dosing.")},
    {id:"rose_co2",name:"Rose CO₂ select/total",desc:"Closer to rose otto aroma at select grades; strong anti-aging positioning.",benefits:{antiaging:3,moisturizing:3,brightening:2},tips:T("Rose luxury without full otto invoice sometimes.","Check select vs total sensory.","Rose CO2-heavy — still $$$ + sensitizers.")},
    {id:"lavender_co2",name:"Lavender CO₂",desc:"Richer, waxier, sometimes higher linalool vs distilled — fuller lavender.",benefits:{calming:3,soothing:3,healing:2},tips:T("Countryside lavender thicker.","Sleep balm premium tier.","Lavender CO2-heavy — muddy if crude.")},
    {id:"carrot_co2",name:"Carrot root CO₂",desc:"Concentrated carotol — stronger vitamin-A direction than carrot seed EO.",benefits:{antiaging:3,brightening:3,regenerating:2},tips:T("Pro-age turbo vs seed EO.","Orange root pigment possible.","Carrot CO2-heavy — soil + color.")},
    {id:"ginger_co2",name:"Ginger CO₂",desc:"Warming CO2 — anti-inflammatory, circulation; rounder than EO sometimes.",benefits:{antiinflammatory:2,antioxidant:2,healing:2},tips:T("Fresh ginger beer vs zinger EO.","Digestive balm crossover.","Ginger CO2-heavy — heat + solvent cost.")},
    {id:"cardamom_co2",name:"Cardamom CO₂",desc:"Clean spicy-sweet CO2; skin-softening chai note.",benefits:{soothing:2,calming:2,antimicrobial:1},tips:T("Milky chai CO2 grace.","Pairs vanilla CO2.","Cardamom CO2-heavy — still spendy.")},
    {id:"blackpepper_co2",name:"Black pepper CO₂",desc:"Warming antioxidant CO2; smoother heat curve than some EOs.",benefits:{antioxidant:2,antiinflammatory:1},tips:T("Velvet pepper vs EO spike.","Masculine dupe layer.","Pepper CO2-heavy — sneeze dust.")},
    {id:"clove_co2",name:"Clove CO₂",desc:"Gentler sensory heat than bud EO in some applications; still eugenol caps apply.",benefits:{antimicrobial:2,antioxidant:2},tips:T("Warm holiday CO2 prickle.","Still respect eugenol limits.","Clove CO2-heavy — numbing risk remains."),potency:"strong"},
    {id:"calendula_co2",name:"Calendula CO₂",desc:"Concentrated faradiol esters — excellent soothing CO2 vs macerated oil story.",benefits:{soothing:3,healing:3,antiinflammatory:2},tips:T("Broken-skin holy grail direction.","Pairs roman chamomile.","Calendula CO2-heavy — orange wax + cost.")},
    {id:"seabuck_co2",name:"Sea buckthorn CO₂ (pulp/seed)",desc:"Concentrated repair; often less insane orange than macerated whole berry oil but still pigment.",benefits:{healing:3,barrier:3,antiinflammatory:2},tips:T("Omega-7 prestige repair.","Still colors balm gold.","Sea buckthorn CO2-heavy — carrot sink stain.")},
    {id:"turmeric_co2",name:"Turmeric CO₂",desc:"Concentrated curcuminoids — stains yellow, very potent anti-inflammatory vs EO.",benefits:{antiinflammatory:3,brightening:2,antioxidant:3},tips:T("Sunset pigment science flex.","Pairs frankincense CO2.","Turmeric CO2-heavy — mustard furniture stain SKU.")},
    {id:"rosehip_co2",name:"Rosehip CO₂ / total extract",desc:"Concentrated trans-retinoic acid angle — strong anti-aging positioning (verify part used).",benefits:{antiaging:3,scarring:2,brightening:2},tips:T("Retinoic-story without synthetic claim care.","Pro-age night balm.","Rosehip CO2-heavy — cost + oxidative sensitivity packaging.")},

    /* —— Resins & oleoresins —— */
    {id:"benzoin_resinoid",name:"Benzoin resinoid",desc:"Vanilla-balsamic skin-healing fixative — thick pourable resin usually pre-diluted.",benefits:{healing:3,soothing:3,calming:2},tips:T("Sticky church incense pour.","Base for every amber.","Resinoid-heavy — benzyl overload.")},
    {id:"vanilla_oleo",name:"Vanilla oleoresin",desc:"Thick concentrated vanilla extract layer — excellent fixative base; often ethanol traces — check VOC policy.",benefits:{calming:2,antioxidant:1},tips:T("Extract gravy base.","Industrial bakery strength.","Oleoresin-heavy — solvent + vanillin crystals.")},
    {id:"tolu_balsam",name:"Tolu balsam",desc:"Warm balsamic wound-healing fixative; cross-allergy with Peru in sensitive cohorts.",benefits:{healing:2,calming:2,soothing:2},tips:T("South American church incense.","Pairs vanilla benzoin.","Tolu-heavy — allergy crosswalk — disclose.")},
    {id:"elemi",name:"Elemi (resin / EO)",desc:"Citrusy-resinous; skin regenerating marketing; pairs frankincense.",benefits:{regenerating:2,healing:2,calming:1},tips:T("Lemon frank opener.","Botanical ‘plastic’ shiny note.","Elemi-heavy — incense bug-spray if cheap.")}
  ];
}
