/**
 * MOSSKYN LAB — Active / Therapeutic Oils (Ingredient B)
 * Migrated from formula_builder_tab.js FB_ING.b
 */

import type { Ingredient } from '@/types';

export const ACTIVES_B: Ingredient[] = [
  { id: 'blackseed', name: 'Black seed', potency: 'strong', desc: 'Thymoquinone is the active — one of the most potent anti-inflammatory plant compounds known. Strong scent.', benefits: { acne: 3, antiinflammatory: 3, antimicrobial: 3 }, tips: { low: 'Safe working dose — thymoquinone active without overwhelming scent.', mid: 'Strong medicinal presence — very effective but scent becomes noticeable.', high: 'Maximum black seed — highly therapeutic but will challenge your EO scent significantly.' } },
  { id: 'neem', name: 'Neem', potency: 'strong', desc: 'Powerful antibacterial and antifungal. Traditional wound-healing. Very pungent.', benefits: { acne: 3, antifungal: 3, antimicrobial: 3 }, tips: { low: 'Minimal neem — antimicrobial effect present, scent manageable.', mid: 'Strong neem activity — effective but requires heavy EO masking.', high: 'Dominant neem — maximum antimicrobial but very hard to mask scent.' } },
  { id: 'tamanu', name: 'Tamanu', potency: 'moderate', desc: 'Calophyllolide is the key active. One of the best oils for scar tissue remodeling. Deep green.', benefits: { scarring: 3, healing: 3, antiinflammatory: 2 }, tips: { low: 'Light tamanu — scar activity begins, subtle green tint.', mid: 'Good scar-remodeling dose — calophyllolide working well.', high: 'Strong tamanu — elite scarring formula, noticeable green tint.' } },
  { id: 'karanja', name: 'Karanja', potency: 'moderate', desc: 'Natural SPF ~20. Pongamol is the active. Milder scent than neem, similar antimicrobial profile.', benefits: { acne: 2, antiinflammatory: 2, antioxidant: 1 }, tips: { low: 'Light UV and antimicrobial support.', mid: 'Good sun-defense and anti-acne dose.', high: 'Strong karanja — significant UV protection layer.' } },
  { id: 'turmeric', name: 'Turmeric CO2', potency: 'strong', desc: 'Curcumin is the active — potent anti-inflammatory and brightener. Will stain yellow.', benefits: { brightening: 3, antiinflammatory: 3, antioxidant: 3 }, tips: { low: 'Trace curcumin — brightening begins, minimal staining.', mid: 'Good brightening and anti-inflammatory — slight yellow tint.', high: 'Strong turmeric — maximum brightening but significant yellow pigment.' } },
  { id: 'bakuchiol', name: 'Bakuchiol', potency: 'moderate', desc: 'Plant-based retinol alternative. Same receptor activity without irritation or photosensitivity.', benefits: { antiaging: 3, firming: 3, healing: 2 }, tips: { low: 'Gentle retinol-like activity — good for daily use intro.', mid: 'Good anti-aging dose — firming and cell renewal active.', high: 'Strong bakuchiol — maximum plant retinol effect.' } },
  { id: 'calendula', name: 'Calendula', potency: 'mild', desc: 'Faradiol is the key active. One of the gentlest and most soothing botanicals. Baby skin safe.', benefits: { soothing: 3, healing: 3, barrier: 2 }, tips: { low: 'Gentle soothing touch — good for sensitive base.', mid: 'Good calming and healing dose — barrier support active.', high: 'Calendula-dominant B — maximally soothing, ideal for reactive or baby skin.' } },
  { id: 'caffeine_extract', name: 'Caffeine extract', potency: 'moderate', desc: 'Bio-derived caffeine for under-eye puffiness, vessel tone, and tired-looking skin. Eye-mode only.', benefits: { circulation: 3, depuffing: 3, firming: 2, antioxidant: 1 }, tips: { low: 'Subtle de-puffing support.', mid: 'Visible vessel-tone and puffiness story.', high: 'Clinic-strength eye-focus — keep away from lash line and broken skin.' } },
  { id: 'licorice_root', name: 'Licorice root extract', potency: 'mild', desc: 'Glabridin-rich botanical for uneven pigment and dark-circle tone support. Gentle enough for eye-area concepts.', benefits: { pigment: 3, brightening: 3, antiinflammatory: 2, soothing: 1 }, tips: { low: 'Soft tone-evening support.', mid: 'Good dark-circle pigment support.', high: 'Licorice-forward brightening story for stubborn under-eye pigment.' } },
  { id: 'tremella', name: 'Tremella mushroom', potency: 'mild', desc: 'Natural polysaccharide plumper with hyaluronic-acid-like water binding for smoother eye texture.', benefits: { plumping: 3, moisturizing: 3, soothing: 2, softening: 2 }, tips: { low: 'Light hydration cushion.', mid: 'Noticeable plumping and smoother texture.', high: 'Tremella-led water cushion for dehydrated fine lines.' } },
  { id: 'moringa', name: 'Moringa', potency: 'mild', desc: 'Behenic acid gives unusual cleansing properties for an oil. Very stable, long shelf life.', benefits: { antioxidant: 2, brightening: 2, barrier: 1 }, tips: { low: 'Light antioxidant and cleansing touch.', mid: 'Good antioxidant presence — mild brightening effect.', high: 'Strong moringa — good cleansing and antioxidant layer.' } },
  { id: 'camellia', name: 'Camellia seed', potency: 'mild', desc: 'Traditional Japanese geisha oil. High oleic, absorbs very fast, extremely elegant skin feel.', benefits: { antiaging: 2, moisturizing: 2, brightening: 1 }, tips: { low: 'Trace elegance — subtle fast-absorbing quality.', mid: 'Good camellia dose — noticeably elegant, fast-absorbing.', high: 'Camellia-dominant B — very elegant. Japanese artisan quality.' } },
  { id: 'gotukola', name: 'Gotu kola (Centella)', potency: 'moderate', desc: 'Asiaticoside / madecassoside family — traditional firmness, scar, and circulation herb.', benefits: { firming: 3, healing: 3, antiaging: 2, scarring: 2 }, tips: { low: 'Intro centella without dominating scent.', mid: 'Solid firming and repair tone.', high: 'Centella-heavy B — intentional herbal direction.' } },
  { id: 'buriti', name: 'Buriti', potency: 'strong', desc: 'Extremely rich in beta-carotene — barrier and photo-damage narrative; deep orange-red.', benefits: { antioxidant: 3, barrier: 3, healing: 2, antiaging: 2 }, tips: { low: 'Trace carotenoid glow — warm tint begins.', mid: 'Noticeable orange tone — patch-test skin and fabrics.', high: 'Buriti-led — treat as color cosmetic adjuvant.' } },
  { id: 'andiroba', name: 'Andiroba', potency: 'moderate', desc: 'Amazonian limonoid-rich oil — traditional use for irritation, muscle, and outdoor skin.', benefits: { antiinflammatory: 3, moisturizing: 2, barrier: 2, healing: 2 }, tips: { low: 'Mild rainforest herbal presence.', mid: 'Good irritation-support dose.', high: 'Andiroba-forward — pair with wood, resin, or spice EOs.' } },
  { id: 'raspberry', name: 'Raspberry seed', potency: 'mild', desc: 'Ellagic acid and EFAs — literature on UV-absorbing fractions. Light, luxury feel.', benefits: { antioxidant: 3, barrier: 2, antiaging: 1 }, tips: { low: 'Outdoor-athlete antioxidant angle.', mid: 'Stronger antioxidant story — still not SPF.', high: 'Raspberry seed–led — "second line" after daily SPF habits.' } },
  { id: 'coffeeoil', name: 'Green coffee', potency: 'mild', desc: 'Chlorogenic acid / caffeine traces — firming and "de-puff" folklore.', benefits: { antioxidant: 2, brightening: 1, firming: 2 }, tips: { low: 'Subtle eye-area / toning story.', mid: 'Roasty note emerges.', high: 'Coffee-heavy B — lean into mocha with vanilla, cacao, or spice EOs.' } },
  { id: 'pumpkin', name: 'Pumpkin seed', potency: 'mild', desc: 'Zinc and phytosterols — mineral-rich soothing nutrition; warm nutty scent.', benefits: { barrier: 2, soothing: 2, moisturizing: 2, healing: 1 }, tips: { low: 'Mineral-rich nuance.', mid: 'Good soothing nutrition dose.', high: 'Pumpkin-led — cozy nutty carrier; beautiful in autumn gourmand scents.' } },
];
