/**
 * MOSSKYN LAB — Carrier Oils (Ingredient A)
 * Migrated from formula_builder_tab.js FB_ING.a
 */

import type { Ingredient } from '@/types';

export const CARRIERS_A: Ingredient[] = [
  { id: 'rosehip', name: 'Rosehip seed', desc: 'Rich in trans-retinoic acid & linoleic acid. Star oil for fading scars and evening skin tone.', benefits: { antiaging: 3, scarring: 3, brightening: 2, barrier: 1 }, tips: { low: 'Light touch of rosehip — adds gentle brightening without dominating.', mid: 'Good working dose — noticeable scar-fading and anti-aging activity.', high: 'Dominant rosehip — this is now your hero A oil. Excellent for mature or scarred skin.' } },
  { id: 'marula', name: 'Marula', desc: 'High oleic acid, absorbs fast. Silky elegant feel that pairs perfectly with tallow without competing.', benefits: { antiaging: 2, moisturizing: 3, barrier: 2 }, tips: { low: 'Subtle marula — mostly adding slip and a silky finish.', mid: 'Good balance — moisturizing activity noticeable, absorbs clean.', high: 'Marula-forward formula — very elegant feel, great for all skin types.' } },
  { id: 'sesame', name: 'Sesame', desc: 'Natural SPF ~4, sesamol is a potent antioxidant. Ayurvedic staple used for millennia on skin.', benefits: { antioxidant: 3, antiinflammatory: 2, barrier: 1 }, tips: { low: 'Mild antioxidant boost — subtle UV defense layer.', mid: 'Solid antioxidant presence — sesamol working actively.', high: 'Strong sesame presence — good antioxidant shield but slight nutty scent note.' } },
  { id: 'baobab', name: 'Baobab', desc: 'Perfectly balanced omega 3-6-9 profile. Very stable oil with long shelf life — adds velvety skin feel.', benefits: { moisturizing: 3, barrier: 3, softening: 2 }, tips: { low: 'Light barrier support — softening effect begins.', mid: 'Good barrier reinforcement — omega balance starting to show.', high: 'Baobab-dominant — exceptional barrier and very stable formula.' } },
  { id: 'argan', name: 'Argan', desc: 'High in squalene and vitamin E naturally. Absorbs clean with no residue. Widely studied.', benefits: { antiaging: 2, brightening: 2, moisturizing: 2 }, tips: { low: 'Light argan presence — subtle brightening and slip.', mid: 'Good working level — anti-aging and brightening active.', high: 'Argan-forward — well-rounded anti-aging carrier, slightly premium feel.' } },
  { id: 'almond', name: 'Sweet almond', desc: 'Gentlest carrier oil available. High in oleic and linoleic. Excellent for sensitive or reactive skin.', benefits: { softening: 3, barrier: 2, soothing: 3 }, tips: { low: 'Mild softening — good base note for sensitive formulas.', mid: 'Noticeably gentle and soothing — ideal sensitive skin dose.', high: 'Very gentle formula — maximally soothing, great for baby or eczema skin.' } },
  { id: 'apricot', name: 'Apricot kernel', desc: 'Similar to almond but lighter. High gamma-linolenic acid. Good facial carrier for mature skin.', benefits: { brightening: 2, antiaging: 1, softening: 2 }, tips: { low: 'Light brightening touch — subtle glow effect.', mid: 'Good balance — brightening and softening both active.', high: 'Apricot-dominant A — lightweight, brightening formula.' } },
  { id: 'hemp', name: 'Hemp seed', desc: 'Perfect 3:1 omega 6:3 ratio mirrors healthy skin lipids. Non-comedogenic. Strong for inflammation.', benefits: { acne: 3, antiinflammatory: 3, barrier: 2 }, tips: { low: 'Gentle anti-inflammatory support — mild acne defense.', mid: 'Good anti-acne dose — omega balance actively supporting skin.', high: 'Hemp-dominant — this is now an anti-inflammatory, anti-acne focused formula.' } },
  { id: 'avocado', name: 'Avocado', desc: 'Penetrates deep skin layers. High in sterols and oleic acid. Best for very dry or cracked skin.', benefits: { moisturizing: 3, barrier: 3, healing: 2 }, tips: { low: 'Deep moisture hint — slightly heavier feel.', mid: 'Good deep moisturizing dose — barrier and healing active.', high: 'Rich, heavy formula — ideal for very dry, cracked or winter skin.' } },
  { id: 'pomegranate', name: 'Pomegranate seed', desc: 'Rare punicic acid (omega-5). Strong antioxidant. Supports collagen synthesis and skin regeneration.', benefits: { antiaging: 3, brightening: 3, antioxidant: 3 }, tips: { low: 'Trace collagen support — antioxidant activity begins.', mid: 'Good anti-aging dose — punicic acid working on skin renewal.', high: 'Pomegranate-dominant — premium anti-aging and brightening formula.' } },
  { id: 'seabuck', name: 'Sea buckthorn', desc: 'Exceptional omega-7, rare in plant oils. Powerful repair oil. Very orange — will tint the balm.', benefits: { healing: 3, barrier: 3, antiaging: 2 }, tips: { low: 'Trace repair activity — minimal tinting at this level.', mid: 'Good repair dose — omega-7 active, slight orange tint likely.', high: 'Strong sea buckthorn — powerful repair but significant orange pigment.' } },
  { id: 'chia', name: 'Chia seed', desc: 'One of the highest plant sources of omega-3. Soothing and film-forming. Relatively new in cosmetics.', benefits: { barrier: 3, antiinflammatory: 2, moisturizing: 2 }, tips: { low: 'Gentle omega-3 addition — light film-forming effect.', mid: 'Good barrier and soothing dose.', high: 'Chia-dominant A — strong omega-3 barrier formula.' } },
  { id: 'squalane', name: 'Squalane', desc: 'Hydrogenated squalene — weightless slip, biomimetic to skin lipids. Stable and almost scent-free.', benefits: { barrier: 3, moisturizing: 3, softening: 2, antiaging: 2 }, tips: { low: 'Trace silkiness — improves spread without weight.', mid: 'Noticeably elegant, skin-identical feel.', high: 'Squalane-forward A — refined texture that stays behind your EO story.' } },
  { id: 'grapeseed', name: 'Grapeseed', desc: 'High linoleic, light dry-touch oil. Popular on oilier or congestion-prone skin; fast to oxidize.', benefits: { acne: 2, barrier: 2, antioxidant: 2, moisturizing: 1 }, tips: { low: 'Light astringent slip — minimal heaviness.', mid: 'Good linoleic support for blemish-prone skin.', high: 'Grapeseed-dominant — very light; use fresh, quality oil.' } },
  { id: 'meadowfoam', name: 'Meadowfoam', desc: 'Long-chain fatty acids — extends oxidative life of softer oils, adds cushioned film.', benefits: { barrier: 3, moisturizing: 2, softening: 2 }, tips: { low: 'Subtle extender — helps protect fragile oils in the mix.', mid: 'Good cushion and stability contribution.', high: 'Meadowfoam-forward — plush, long-wearing after-feel.' } },
  { id: 'ricebran', name: 'Rice bran', desc: 'Gamma-oryzanol and ferulic acid — brightening-leaning antioxidant support. Classic in Asian skin care.', benefits: { brightening: 2, antioxidant: 3, moisturizing: 2, antiaging: 1 }, tips: { low: 'Light nutrient boost for tone and oxidative cover.', mid: 'Working antioxidant dose — pairs with vitamin E.', high: 'Rice bran–heavy — richer feel, stronger brightening story.' } },
  { id: 'sunflower', name: 'Sunflower (high linoleic)', desc: 'Linoleic-rich grades support barrier repair; neutral, affordable carrier.', benefits: { barrier: 3, soothing: 2, moisturizing: 2 }, tips: { low: 'Gentle barrier filler — stays behind the scent.', mid: 'Solid linoleic support for compromised barriers.', high: 'Sunflower-dominant — economical, calming base.' } },
  { id: 'macadamia', name: 'Macadamia', desc: 'Palmitoleic acid (omega-7) mirrors youthful skin sebum — lush on mature or very dry skin.', benefits: { moisturizing: 3, antiaging: 2, softening: 3, barrier: 2 }, tips: { low: 'Hint of richness — subtle mature-skin support.', mid: 'Good omega-7 dose — silky, nourishing.', high: 'Macadamia-led — lush, elegant dry-skin formula.' } },
  { id: 'eveprim', name: 'Evening primrose', desc: 'GLA-rich — traditional support for hormonal skin, redness, and barrier stress.', benefits: { antiinflammatory: 3, barrier: 2, soothing: 2, healing: 1 }, tips: { low: 'Gentle GLA hint — mild calming.', mid: 'Meaningful GLA activity — soothing barrier support.', high: 'Primrose-forward — watch freshness (polyunsaturated).' } },
  { id: 'borage', name: 'Borage', desc: 'Among the highest GLA sources — intense for very dry, flaky, or stressed skin; heavier feel.', benefits: { barrier: 3, moisturizing: 3, antiinflammatory: 2, healing: 2 }, tips: { low: 'Light GLA addition.', mid: 'Strong barrier and calming dose.', high: 'Borage-dominant — very rich; winter or dermatitis-prone angle.' } },
  { id: 'pricklypear', name: 'Prickly pear seed', desc: 'Luxury — very high tocopherols and linoleic acid; fast absorption, dry finish.', benefits: { antioxidant: 3, brightening: 2, barrier: 2, antiaging: 2 }, tips: { low: 'Trace luxury antioxidant.', mid: 'Clear antioxidant + tone support.', high: 'Prickly pear–led — premium, serum-light major carrier.' } },
  { id: 'watermelon', name: 'Watermelon seed', desc: 'Ultra-light "dry" oil — high linoleic, minimal shine; good when you want A without heaviness.', benefits: { acne: 2, moisturizing: 1, barrier: 2, softening: 2 }, tips: { low: 'Barely-there slip.', mid: 'Featherweight texture for congestion-prone skin.', high: 'Watermelon-dominant — major carrier that still feels weightless.' } },
];
