/**
 * MOSSKYN LAB — Exfoliant ingredients (Ingredient C)
 * Migrated from formula_builder_c_list.js
 */

import type { Ingredient } from '@/types';

export const EXFOLIANTS_C: Ingredient[] = [
  { id: 'sugar', name: 'Sugar (fine or raw)', desc: 'Gentler than salt; sugar dissolves on contact with damp skin, so it is less likely to over-strip than harsh salt scrubs.', benefits: { softening: 2, soothing: 2 }, tips: { low: 'Soft polish — beginner-friendly body scrub.', mid: 'Noticeable slip and melt as you work.', high: 'Sugar-heavy — still buff gently; rinse thoroughly.' } },
  { id: 'coffee_grounds', name: 'Coffee grounds', desc: 'Antioxidant-rich; medium grit — great for body circulation stories and morning ritual scent.', benefits: { antioxidant: 3, antiinflammatory: 1, softening: 1 }, tips: { low: 'Mild wake-up grit — spa-café vibe.', mid: 'Working body polish — pair with cocoa or vanilla EOs.', high: 'Coffee-forward — can feel scratchy on thin facial skin; bias to body.' } },
  { id: 'oat_flour', name: 'Oat flour', desc: 'Ultra-gentle; anti-inflammatory — ideal for sensitive, eczema-leaning, or face-safe exfoliator.', benefits: { soothing: 3, antiinflammatory: 3, barrier: 2, softening: 2 }, tips: { low: 'Featherweight polish — milky calm.', mid: 'Dominant sensitive-skin story.', high: 'Oat-led — can clump if oil phase is cool; fold evenly.' } },
  { id: 'clay_polish', name: 'Bentonite / kaolin clay', desc: 'Not grainy like sugar — offers mild polishing drag while drawing oil and impurities.', benefits: { acne: 2, brightening: 1, barrier: 1 }, tips: { low: 'Clay whisper — refines slip.', mid: 'Balancing "second cleanse" body paste feel.', high: 'Clay-heavy — watch dryness on already stripped skin; moisturize after.' } },
  { id: 'walnut_apricot', name: 'Walnut / apricot shell powder', desc: 'Finer, more controlled abrasion than coarse salt; still physically abrasive.', benefits: { softening: 1 }, potency: 'strong', tips: { low: 'Controlled buff for knees/elbows.', mid: 'Visible polish — avoid aggressive circles.', high: 'Abrasive-forward — micro-scratch risk if cheap grind; face caution.' } },
  { id: 'baking_soda', name: 'Baking soda (sodium bicarbonate)', desc: 'Very fine micro-grit feel; can be mildly pH-shifting — gentle marketing and patch-test.', benefits: { brightening: 1, softening: 1 }, potency: 'moderate', tips: { low: 'Almost imperceptible grit — "polished skin" marketing.', mid: 'Pairs oat or clay to buffer feel.', high: 'Baking soda-heavy — alkalinity concerns on sensitive skin.' } },
  { id: 'ground_ginger', name: 'Ground ginger', desc: 'Warming, circulation-boosting exfoliant with anti-inflammatory gingerols. Fine texture with mild heat sensation.', benefits: { antiinflammatory: 3, antioxidant: 2, brightening: 2 }, potency: 'moderate', tips: { low: 'Subtle warmth — pairs well with citrus EOs.', mid: 'Noticeable tingle — great for body circulation scrubs.', high: 'Ginger-forward — can feel hot on sensitive skin; patch test first.' } },
  { id: 'charcoal', name: 'Activated charcoal', desc: 'Ultra-fine cleansing powder for oil-absorbing, pore-focused cleaner formulas. Use lightly to avoid a drying, messy feel.', benefits: { poreClearing: 3, sebumControl: 2, acne: 2 }, potency: 'moderate', tips: { low: 'Soft grey cleansing cue — subtle oil pull.', mid: 'Visible charcoal story with pore-clearing focus.', high: 'Charcoal-forward — can feel drying and stain towels; keep body/spot use in mind.' } },
  { id: 'sea_salt_cleaner', name: 'Sea salt (fine)', desc: 'Mineral-rich salt exfoliant that gives a rustic spa-polish feel. Best for body-focused cleaners, not delicate facial skin.', benefits: { exfoliation: 3, softening: 1 }, potency: 'strong', tips: { low: 'Light mineral polish.', mid: 'Noticeable salt-scrub feel for body formulas.', high: 'Salt-heavy — abrasive and potentially drying; avoid sensitized skin.' } },
];
