/**
 * MOSSKYN LAB — Soap Oils with real SAP values
 * Sources: Bramble Berry, SoapCalc, Certified Lye
 */

import type { SoapOil } from '@/types';

export const SOAP_OILS: SoapOil[] = [
  {
    id: 'beef_tallow',
    name: 'Beef Tallow (rendered)',
    sapNaOH: 0.1405,
    sapKOH: 0.1970,
    hardness: 58,
    cleansing: 12,
    conditioning: 43,
    bubbly: 12,
    creamy: 47,
    iodine: 42,
    defaultPct: 55,
    desc: 'The backbone of MOSSKYN LAB soap. Produces an incredibly hard, long-lasting bar with creamy, stable lather. Rich in stearic and oleic acids — the same lipid profile as human sebum.',
    category: 'base',
  },
  {
    id: 'olive_pomace',
    name: 'Olive Oil (Pomace)',
    sapNaOH: 0.1340,
    sapKOH: 0.1880,
    hardness: 17,
    cleansing: 0,
    conditioning: 82,
    bubbly: 0,
    creamy: 17,
    iodine: 85,
    defaultPct: 25,
    desc: 'Major conditioning carrier. Pomace grade traces faster than EVOO and produces a harder bar. Ancient Castile soap heritage — pure olive soap has been made for millennia.',
    category: 'base',
  },
  {
    id: 'coconut_76',
    name: 'Coconut Oil (76°)',
    sapNaOH: 0.1787,
    sapKOH: 0.2507,
    hardness: 79,
    cleansing: 67,
    conditioning: 10,
    bubbly: 67,
    creamy: 14,
    iodine: 10,
    defaultPct: 10,
    desc: 'Provides big, bubbly lather and hardness. Keep at 10-15% to avoid drying — lauric acid cleansing is powerful but strips at high percentages.',
    category: 'base',
  },
  {
    id: 'castor',
    name: 'Castor Oil',
    sapNaOH: 0.1286,
    sapKOH: 0.1804,
    hardness: 0,
    cleansing: 0,
    conditioning: 95,
    bubbly: 90,
    creamy: 90,
    iodine: 86,
    defaultPct: 5,
    desc: 'Lather booster and stabiliser. Ricinoleic acid creates thick, creamy bubbles that cling. Acts as a humectant. Keep at 5-8% — too much creates sticky, soft bars.',
    category: 'carrier',
  },
  {
    id: 'beeswax',
    name: 'Beeswax',
    sapNaOH: 0.0694,
    sapKOH: 0.0973,
    hardness: 90,
    cleansing: 0,
    conditioning: 5,
    bubbly: 0,
    creamy: 2,
    iodine: 8,
    defaultPct: 3,
    desc: 'Extreme hardener and unmolding aid. Creates a beautiful sheen on the bar surface. Keep at 2-4% — inhibits lather at higher percentages. Lower SAP value noted.',
    category: 'luxury',
  },
  {
    id: 'shea_butter',
    name: 'Shea Butter (unrefined)',
    sapNaOH: 0.1280,
    sapKOH: 0.1795,
    hardness: 45,
    cleansing: 0,
    conditioning: 65,
    bubbly: 0,
    creamy: 46,
    iodine: 59,
    defaultPct: 2,
    desc: 'Luxury unsaponifiables (up to 11%) survive saponification and condition skin. Adds creaminess without cleaning power. Premium feel and marketing story.',
    category: 'luxury',
  },
  {
    id: 'palm',
    name: 'Palm Oil (RSPO)',
    sapNaOH: 0.1410,
    sapKOH: 0.1977,
    hardness: 50,
    cleansing: 1,
    conditioning: 49,
    bubbly: 1,
    creamy: 49,
    iodine: 53,
    defaultPct: 0,
    desc: 'Traditional soap hardener. Similar fatty-acid profile to tallow but plant-based. RSPO-certified only. Not in the default MOSSKYN LAB recipe — tallow replaces it.',
    category: 'base',
  },
  {
    id: 'avocado_soap',
    name: 'Avocado Oil',
    sapNaOH: 0.1330,
    sapKOH: 0.1865,
    hardness: 16,
    cleansing: 0,
    conditioning: 82,
    bubbly: 0,
    creamy: 16,
    iodine: 86,
    defaultPct: 0,
    desc: 'Deeply conditioning with high unsaponifiables. Penetrates skin layers. Softer bar — combine with tallow or coconut for structure. Luxury positioning.',
    category: 'carrier',
  },
  {
    id: 'rice_bran_soap',
    name: 'Rice Bran Oil',
    sapNaOH: 0.1284,
    sapKOH: 0.1802,
    hardness: 26,
    cleansing: 0,
    conditioning: 64,
    bubbly: 0,
    creamy: 26,
    iodine: 103,
    defaultPct: 0,
    desc: 'Gamma oryzanol and ferulic acid — brightening antioxidant. Budget-friendly olive alternative with a slightly firmer bar. Asian skincare heritage.',
    category: 'carrier',
  },
  {
    id: 'sweet_almond_soap',
    name: 'Sweet Almond Oil',
    sapNaOH: 0.1360,
    sapKOH: 0.1907,
    hardness: 19,
    cleansing: 0,
    conditioning: 78,
    bubbly: 0,
    creamy: 19,
    iodine: 99,
    defaultPct: 0,
    desc: 'Gentle, conditioning, mild. Oleic-rich like olive but lighter skin feel. Excellent for sensitive-skin soap formulations.',
    category: 'carrier',
  },
  {
    id: 'cocoa_butter',
    name: 'Cocoa Butter',
    sapNaOH: 0.1378,
    sapKOH: 0.1933,
    hardness: 61,
    cleansing: 0,
    conditioning: 56,
    bubbly: 0,
    creamy: 61,
    iodine: 37,
    defaultPct: 0,
    desc: 'Very hard bar, rich chocolate aroma. High stearic acid. Keep at 5-15% — too much creates crumbly, brittle bars. Incredible in combination with tallow.',
    category: 'luxury',
  },
  {
    id: 'mango_butter',
    name: 'Mango Butter',
    sapNaOH: 0.1280,
    sapKOH: 0.1795,
    hardness: 44,
    cleansing: 0,
    conditioning: 62,
    bubbly: 0,
    creamy: 44,
    iodine: 55,
    defaultPct: 0,
    desc: 'Similar to shea but firmer. High in oleic and stearic. Moisturizing without being heavy — tropical luxury feel.',
    category: 'luxury',
  },
];

export function getDefaultSoapOils(): SoapOil[] {
  return SOAP_OILS.filter(o => o.defaultPct > 0);
}

export function getSoapOilById(id: string): SoapOil | undefined {
  return SOAP_OILS.find(o => o.id === id);
}
